/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 122019465ffb7dbce21d8088685e82e5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "DatabaseDurableObject";
	}
	interface Env {
		DATABASE: DurableObjectNamespace<import("./src/worker").DatabaseDurableObject>;
		EMAIL: SendEmail;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
